### ISSUE TITLE
В чат не линкуются предметы/ачивы

### ISSUE THREAD

**Issue by priestjkeee** [k0w4lk/CraftsmanHelper_Options#1]
Если включен аддон CraftsmanHelper_Options , то в чат перестают линковаться предметы/ачивы.

Предусловие:

1. Зайти в игру
2. Включить аддон CraftsmanHelper_Options 

Шаги:

1. Открыть поле ввода текста в любом чате
2. Сочетанием клавиш Shift+Left click добавить ссылку на любой предмет в чат

Ожидаемый результат:
Ссылка на предмет появилась в поле ввода текста

Фактический результат:
Поле ввода текста осталось пустым

**Comment by priestjkeee** [comment]
![Wowcircle 3 3 5a 2024 11 14 - 10 31 20 01](https://github.com/user-attachments/assets/21fabfbc-1769-44de-ad08-02ed3dad0bd4)

**Comment by k0w4lk** [comment]
fixed in release 1.0.1
